services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    hostname: qbittorrent.internal
    ports:
      - "8080:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp
      - LIBTORRENT=v1
      # VPN
      - VPN_ENABLED=true 
      - VPN_CONF=wg0 
      - VPN_PROVIDER=pia 
      - VPN_LAN_NETWORK=192.168.1.0/24,100.64.0.0/10
      - VPN_LAN_LEAK_ENABLED=false 
      - VPN_AUTO_PORT_FORWARD=true 
      - VPN_HEALTHCHECK_ENABLED=true
      - VPN_PIA_PREFERRED_REGION=ca_toronto
      - VPN_PIA_USER=${VPN_PIA_USER}
      - VPN_PIA_PASS=${VPN_PIA_PASS}
      - VPN_PIA_PORT_FORWARD_PERSIST=true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./qbittorrent_config/:/config
      - /mnt/hdd1/qbittorrent:/qbittorrent
    env_file:
      - .env
    networks:
      - arr
  
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ./prowlarr_config:/config
    networks:
      - arr

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    ports:
      - "8686:8686"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ./lidarr_config:/config
      - /mnt/hdd1/qbittorrent:/qbittorrent
    networks:
      - arr

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ./radarr_config:/config
      - /mnt/hdd1/qbittorrent:/qbittorrent
    networks:
      - arr

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ./sonarr_config:/config
      - /mnt/hdd1/qbittorrent:/qbittorrent
    networks:
      - arr

  seerr:
    container_name: seerr
    image: ghcr.io/hotio/seerr
    ports:
      - "5055:5055"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ./seerr_config:/config
    networks:
      - arr

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
    networks:
      - arr

networks:
  arr:
    name: arr
