services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    hostname: qbittorrent.internal
    ports:
      - "8080:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp
      - LIBTORRENT=v1
      # VPN
      - VPN_ENABLED=true 
      - VPN_CONF=wg0 
      - VPN_PROVIDER=pia 
      - VPN_LAN_NETWORK=192.168.1.0/24,100.64.0.0/10
      - VPN_LAN_LEAK_ENABLED=false 
      - VPN_EXPOSE_PORTS_ON_LAN 
      - VPN_AUTO_PORT_FORWARD=true 
      - VPN_HEALTHCHECK_ENABLED=false 
      - VPN_PIA_USER=${VPN_PIA_USER}
      - VPN_PIA_PASS=${VPN_PIA_PASS}
      - VPN_PIA_PORT_FORWARD_PERSIST=false 
    cap_add:
      - NET_ADMIN
    volumes:
      - ./qbittorrent_config/:/config
      - /mnt/hdd1/qbittorrent:/qbittorrent
    env_file:
      - .env
    networks:
      - arr
  
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=9696/tcp 
    volumes:
      - ./prowlarr_config:/config
    networks:
      - arr

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    ports:
      - "8686:8686"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8686/tcp 
    volumes:
      - ./lidarr_config:/config
      - /mnt/hdd1/qbittorrent:/qbittorrent
    networks:
      - arr

networks:
  arr:
    name: arr
