services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1000:1001"
    ports:
      - 8888:8080
    volumes:
      - /mnt/hdd1/media:/data/media
      - /mnt/hdd1/qbittorrent:/data/qbittorrent
      - ./filebrowser_config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: "always"
