services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1000:1001"
    ports:
      - 8888:8080
    volumes:
      - /mnt/hdd1/media:/data/media
      - /mnt/hdd1/qbittorrent:/data/qbittorrent
      - ./filebrowser_config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: "always"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
    environment:
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL'
      FTLCONF_dns_listeningMode: 'ALL'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
